### PR TITLE
fix(types): make number assignable

### PR DESCRIPTION
**Pull request by sambacha**
Argument of type 'number' is not assignable to parameter of type 'never'.ts(2345)

### CODE REVIEW

**Comment by sambacha** [comment]
my tsconfig looks like this for reference:

```json
{
  "$schema": "https://json.schemastore.org/tsconfig",
  "compilerOptions": {
    "allowSyntheticDefaultImports": false,
    "esModuleInterop": false,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "removeComments": true,
    "incremental": true,
    "tsBuildInfoFile": "./",
    "preserveValueImports": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowUnreachableCode": false,
    "strictPropertyInitialization": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "isolatedModules": true,
    "declaration": true,
    "sourceMap": false,
    "module": "node16",
    "moduleResolution": "node16",
    "moduleDetection": "force",
    "target": "ESNext",
    "rootDir": "./src",
    "outDir": "./dist",
    "types": [],
    "plugins": [
      {
        "name": "typescript-eslint-language-service"
      }
    ]
  },
  "include": [
    "src/**/*.ts"
  ],
  "exclude": [
    "**/node_modules",
    "**/.*/",
    "src/**/*.test.ts"
  ]
}

```

**Comment by MicahZoltu** [comment]
You are doing a custom build?  What version of Typescript are you using?

The compiler should be able to infer the type here, the explicit type shouldn't be necessary.  I'll try to reproduce your error later today to verify.

**Comment by MicahZoltu** [comment]
I just double checked that the project compiles with what is committed in this repository.  What steps are you going through to try to build it?

**Comment by MicahZoltu** [comment]
I also just double checked and it compiles with TypeScript v4.7.4 (latest) as well.

**Comment by sambacha** [comment]
Screen Shot 2022-06-20 at 12 09 58 AM


To be sure this does compile, that I had no issues with. I just saw this and thought it should come to your attention as this is the best typed ethereum library that I know of

**Comment by sambacha** [comment]
For reference, I am considering different options for the new sushiswap routing contract for their new front end. 

Any suggestions are welcomed

**Comment by MicahZoltu** [comment]
Ah, you are probably using an old version of the TypeScript compiler in your editor.  Is that VSCode?  If so, then #2 should resolve the issue.

My general recommendation to people is to use ethers.js, in particular their new v6 version (currently in beta, expect many bugs).  It is actively maintained, documented, and well supported.  With the introduction of v6, it no longer brings in a ton of third party dependencies and it now uses native JS dependency-free crypto libraries.  It also natively supports `bigint`s for a lot of things.

I don't agree with all of the design decisions that ricmoo made in ethers, but I think it is the best option at the moment.  Also, this library isn't actively maintained anymore unfortunately, so only use it if it is pretty close to what you want already or if you want to fork it and maintain that fork yourself.

**Comment by sambacha** [comment]
> Ah, you are probably using an old version of the TypeScript compiler in your editor. Is that VSCode? If so, then #2 should resolve the issue.
> 
> My general recommendation to people is to use ethers.js, in particular their new v6 version (currently in beta, expect many bugs). It is actively maintained, documented, and well supported. With the introduction of v6, it no longer brings in a ton of third party dependencies and it now uses native JS dependency-free crypto libraries. It also natively supports `bigint`s for a lot of things.
> 
> I don't agree with all of the design decisions that ricmoo made in ethers, but I think it is the best option at the moment. Also, this library isn't actively maintained anymore unfortunately, so only use it if it is pretty close to what you want already or if you want to fork it and maintain that fork yourself.

yup, much appreciated for the reminder of v6. I am going to close this, thanks as always @MicahZoltu

**Comment by sambacha** [comment]
This was in my IDE , vscode alerting to the issue. Yes it does compile
without the change. I am doing a custom compile as I want a pure esm build
for checking against.

Im on node 18 as well

**Comment by MicahZoltu** [comment]
In VSCode, you can open the command palette while you have a `.ts` file opened in the editor and look for `TypeScript: Select TypeScript Version...`.  This should show you what version of TS is being used, and if it doesn't match what the project uses it may not work.  You can tell VSCode (via that same menu) to use the "workspace version", which should resolve the problem.

**Comment by sambacha** [comment]
> In VSCode, you can open the command palette while you have a `.ts` file opened in the editor and look for `TypeScript: Select TypeScript Version...`. This should show you what version of TS is being used, and if it doesn't match what the project uses it may not work. You can tell VSCode (via that same menu) to use the "workspace version", which should resolve the problem.

Hey Micah, apologies for this, seems as though my GitHub notifications app is auto-responding, 




Sorry !

**Pull request closed without merging**
